server:
  port: 8082
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ribbon:
  ConnectTimeout: 250
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

logging:
  level:
    com.hxtcoder.consumerservice.client: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
feign:
#  client:
#    config:
#      default:
#        connectTimeout: 250
#        readTimeout: 1000

  hystrix:
    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types: text/html,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true
